// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBr_Cx1W9zktbZBE1mwzLtYb0bvmL0hwA',
    appId: '1:155688357973:web:a5f0d845ae7a0b1cd1c4dc',
    messagingSenderId: '155688357973',
    projectId: 'gonespoti-1a20b',
    authDomain: 'gonespoti-1a20b.firebaseapp.com',
    storageBucket: 'gonespoti-1a20b.firebasestorage.app',
    measurementId: 'G-MYCGV6BF8M',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEk71FEk44KIAwJxe7Kkhi819qIWlO0a4',
    appId: '1:155688357973:android:239df2e0301b6b21d1c4dc',
    messagingSenderId: '155688357973',
    projectId: 'gonespoti-1a20b',
    storageBucket: 'gonespoti-1a20b.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDarlIXz5dD4hDzJ7Rg9MeE5DBF3DBFwUw',
    appId: '1:155688357973:ios:6f2a73d51367ffc9d1c4dc',
    messagingSenderId: '155688357973',
    projectId: 'gonespoti-1a20b',
    storageBucket: 'gonespoti-1a20b.firebasestorage.app',
    iosBundleId: 'com.example.ridesharing',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDarlIXz5dD4hDzJ7Rg9MeE5DBF3DBFwUw',
    appId: '1:155688357973:ios:6f2a73d51367ffc9d1c4dc',
    messagingSenderId: '155688357973',
    projectId: 'gonespoti-1a20b',
    storageBucket: 'gonespoti-1a20b.firebasestorage.app',
    iosBundleId: 'com.example.ridesharing',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBr_Cx1W9zktbZBE1mwzLtYb0bvmL0hwA',
    appId: '1:155688357973:web:e6a37e3c2cebb13bd1c4dc',
    messagingSenderId: '155688357973',
    projectId: 'gonespoti-1a20b',
    authDomain: 'gonespoti-1a20b.firebaseapp.com',
    storageBucket: 'gonespoti-1a20b.firebasestorage.app',
    measurementId: 'G-ZFPN5L2ERS',
  );
}
